# Generated by Django 4.2.30 on 2026-06-21 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "max_temp",
                    models.IntegerField(
                        help_text="Максимальная температура сопла в градусах Цельсия"
                    ),
                ),
                (
                    "build_volume_m3",
                    models.FloatField(
                        help_text="Объем рабочей зоны в кубических метрах"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
            },
        ),
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="printers.equipment",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Серийный номер"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата покупки"
                    ),
                ),
                (
                    "warranty_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Конец гарантии"
                    ),
                ),
                (
                    "working_hours",
                    models.FloatField(default=0, verbose_name="Отработанные часы"),
                ),
                (
                    "technology",
                    models.CharField(
                        default="FDM", max_length=20, verbose_name="Технология"
                    ),
                ),
                (
                    "bed_size_x",
                    models.FloatField(default=200, verbose_name="Размер стола X (мм)"),
                ),
                (
                    "bed_size_y",
                    models.FloatField(default=200, verbose_name="Размер стола Y (мм)"),
                ),
                (
                    "bed_size_z",
                    models.FloatField(default=200, verbose_name="Размер стола Z (мм)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Ожидание"),
                            ("printing", "Печать"),
                            ("maintenance", "Обслуживание"),
                        ],
                        default="idle",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Принтер",
                "verbose_name_plural": "Принтеры",
            },
            bases=("printers.equipment",),
        ),
    ]
