# Generated by Django 4.2.30 on 2026-06-13 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(choices=[('filament', 'Материалы (филаменты)'), ('consumable', 'Расходные материалы'), ('packaging', 'Упаковочные материалы')], default='filament', max_length=20, verbose_name='Категория')),
                ('material_type', models.CharField(default='PLA', max_length=50, verbose_name='Тип материала')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Производитель')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='Поставщик')),
                ('color_hex', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет (HEX)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за кг')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена закупки')),
                ('weight_g', models.FloatField(default=0, verbose_name='Остаток на складе (г)')),
                ('actual_weight_g', models.FloatField(default=0, verbose_name='Фактический остаток (г)')),
                ('previous_inventory_date', models.DateField(blank=True, null=True, verbose_name='Дата прошлой инвентаризации')),
                ('next_inventory_date', models.DateField(blank=True, null=True, verbose_name='Дата следующей инвентаризации')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('min_weight_g', models.FloatField(default=0, verbose_name='Минимальный остаток (г)')),
                ('density', models.FloatField(default=1.25, verbose_name='Плотность (г/см3)')),
                ('print_temperature_c', models.IntegerField(blank=True, null=True, verbose_name='Температура печати (°C)')),
                ('filament_diameter_mm', models.FloatField(blank=True, null=True, verbose_name='Диаметр нити (мм)')),
                ('spool_weight_g', models.FloatField(blank=True, null=True, verbose_name='Вес катушки (г)')),
                ('filament_length_m', models.FloatField(blank=True, null=True, verbose_name='Длина нити (м)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('processing', 'В обработке'), ('printing', 'Печать'), ('finished', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка часа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Последнее ТО')),
                ('max_temp', models.IntegerField(default=300, verbose_name='Максимальная температура сопла (°C)')),
                ('build_volume', models.CharField(default='220x220x250', max_length=50, verbose_name='Объем рабочей зоны')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('preview', 'Предпросмотр'), ('repairing', 'На ремонте'), ('slicing', 'В нарезке'), ('ready_to_print', 'Готов к печати'), ('printing', 'Печать'), ('logistics', 'Передан в логистику'), ('completed', 'Доставлен'), ('failed', 'Ошибка')], default='draft', max_length=20)),
                ('upload_kind', models.CharField(choices=[('model', '3D-модель'), ('sketch', 'Эскиз / 2D')], default='model', max_length=10, verbose_name='Тип загрузки')),
                ('sketch_width_mm', models.FloatField(blank=True, null=True, verbose_name='Ширина эскиза (мм)')),
                ('sketch_height_mm', models.FloatField(blank=True, null=True, verbose_name='Высота эскиза (мм)')),
                ('sketch_thickness_mm', models.FloatField(blank=True, null=True, verbose_name='Толщина эскиза (мм)')),
                ('original_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('converted_stl', models.FileField(blank=True, null=True, upload_to='stl/')),
                ('converted_glb', models.FileField(blank=True, null=True, upload_to='glb/')),
                ('converted_3mf', models.FileField(blank=True, null=True, upload_to='3mf/')),
                ('gcode_file', models.FileField(blank=True, null=True, upload_to='gcode/')),
                ('estimated_weight', models.FloatField(blank=True, null=True, verbose_name='Расчетный вес (г)')),
                ('estimated_time_minutes', models.IntegerField(blank=True, null=True, verbose_name='Расчетное время (мин)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Финальная цена')),
                ('moonraker_job_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Moonraker job ID')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задание на печать',
                'verbose_name_plural': 'Задания на печать',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintJobSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('index', models.PositiveIntegerField(verbose_name='Индекс')),
                ('selected', models.BooleanField(default=False, verbose_name='Выбрано')),
                ('slot_assignment', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Назначение слота')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='core.printjob')),
            ],
            options={
                'verbose_name': 'Поверхность модели',
                'verbose_name_plural': 'Поверхности модели',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('print_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.printjob')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='print_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.printjob'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PrintJobMaterialAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveSmallIntegerField(verbose_name='Индекс слота')),
                ('length_mm', models.FloatField(blank=True, null=True, verbose_name='Длина (мм)')),
                ('mass_g', models.FloatField(blank=True, null=True, verbose_name='Масса (г)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_assignments', to='core.printjob')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Назначение материала',
                'verbose_name_plural': 'Назначения материалов',
                'ordering': ['slot_index'],
                'unique_together': {('job', 'slot_index')},
            },
        ),
    ]
