# Generated by Django 4.2.30 on 2026-06-30 21:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирована"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершена"),
                            ("canceled", "Отменена"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("planned_date", models.DateField(verbose_name="Планируемая дата")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершено"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Инвентаризация",
                "verbose_name_plural": "Инвентаризации",
                "ordering": ["-planned_date"],
            },
        ),
        migrations.CreateModel(
            name="InventoryAuditItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_quantity",
                    models.IntegerField(default=0, verbose_name="Системное количество"),
                ),
                (
                    "actual_quantity",
                    models.IntegerField(
                        default=0, verbose_name="Фактическое количество"
                    ),
                ),
                ("difference", models.IntegerField(default=0, verbose_name="Разница")),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Проверено"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Проверено"
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент инвентаризации",
                "verbose_name_plural": "Элементы инвентаризации",
            },
        ),
        migrations.CreateModel(
            name="WarehouseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("material", "Материал"),
                            ("consumable", "Расходник"),
                            ("equipment", "Оборудование"),
                        ],
                        default="material",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Артикул"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "min_quantity",
                    models.IntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Минимальный остаток",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="шт.", max_length=50, verbose_name="Единица измерения"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Себестоимость",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Цена продажи",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Поставщик"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Местоположение"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Элемент склада",
                "verbose_name_plural": "Элементы склада",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "Приход"),
                            ("expense", "Расход"),
                            ("transfer", "Перемещение"),
                            ("adjustment", "Корректировка"),
                        ],
                        max_length=20,
                        verbose_name="Тип транзакции",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "old_quantity",
                    models.IntegerField(default=0, verbose_name="Старое количество"),
                ),
                (
                    "new_quantity",
                    models.IntegerField(default=0, verbose_name="Новое количество"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="warehouse.warehouseitem",
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_transactions",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция склада",
                "verbose_name_plural": "Транзакции склада",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="warehouseitem",
            index=models.Index(fields=["sku"], name="warehouse_w_sku_e1e096_idx"),
        ),
        migrations.AddIndex(
            model_name="warehouseitem",
            index=models.Index(
                fields=["item_type"], name="warehouse_w_item_ty_f17520_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehouseitem",
            index=models.Index(
                fields=["is_active"], name="warehouse_w_is_acti_f070a6_idx"
            ),
        ),
        migrations.AddField(
            model_name="inventoryaudititem",
            name="audit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="warehouse.inventoryaudit",
            ),
        ),
        migrations.AddField(
            model_name="inventoryaudititem",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_audit_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventoryaudititem",
            name="warehouse_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_items",
                to="warehouse.warehouseitem",
            ),
        ),
        migrations.AddField(
            model_name="inventoryaudit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_audits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="warehousetransaction",
            index=models.Index(fields=["item"], name="warehouse_w_item_id_a8eaba_idx"),
        ),
        migrations.AddIndex(
            model_name="warehousetransaction",
            index=models.Index(
                fields=["transaction_type"], name="warehouse_w_transac_77619e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousetransaction",
            index=models.Index(
                fields=["created_at"], name="warehouse_w_created_0f129a_idx"
            ),
        ),
    ]
