from __future__ import annotations

import json
import os
import subprocess
from decimal import Decimal
from pathlib import Path

from celery import shared_task
from django.conf import settings
from django.core.files.base import ContentFile

from .models import MaterialPreset, PrintJob, SlotAssignment
from .services.moonraker import MoonrakerClient


@shared_task(bind=True, max_retries=0)
def slice_and_analyze_task(self, job_id: int) -> None:
    job = PrintJob.objects.get(pk=job_id)
    job.last_error = ""
    job.save(update_fields=["last_error"])

    stl_path = Path(job.converted_stl.path if job.converted_stl else job.original_file.path)

    try:
        if getattr(settings, "SLICER_MODE", "mock") == "mock":
            _mock_slice(job, stl_path)
            return

        gcode_path = stl_path.with_suffix(".gcode")
        stats_path = stl_path.with_suffix("").as_posix() + "_stats.json"

        orca = getattr(settings, "ORCASLICER_PATH", "") or ""
        profile = getattr(settings, "ORCASLICER_PROFILE", "") or ""
        if not orca or not Path(orca).exists():
            raise RuntimeError("ORCASLICER_PATH не задан или файл не найден")

        cmd = [
            orca,
            "--input",
            str(stl_path),
            "--output",
            str(gcode_path),
            "--profile",
            profile,
            "--export-stats",
            stats_path,
        ]
        subprocess.run(cmd, check=True, timeout=600)

        with open(stats_path, encoding="utf-8") as f:
            stats = json.load(f)

        job.slot_assignments.all().delete()
        for s in stats.get("slots", []):
            SlotAssignment.objects.create(
                job=job,
                slot_index=int(s["index"]),
                material_preset_id=int(s["material_preset_id"]),
                length_mm=float(s.get("length_mm", 0)),
                mass_g=float(s.get("mass_g", 0)),
                cost=Decimal(str(s.get("cost", "0"))),
            )

        with open(gcode_path, "rb") as f:
            job.gcode_file.save(os.path.basename(gcode_path), ContentFile(f.read()), save=False)

        moonraker = MoonrakerClient()
        filename = moonraker.upload_gcode(job.gcode_file.path)
        job.moonraker_job_id = moonraker.start_print(filename) or ""

        job.status = "ready"
        job.save()
    except Exception as exc:
        job.status = "error"
        job.last_error = str(exc)
        job.save()


def _mock_slice(job: PrintJob, stl_path: Path) -> None:
    """Демо без реального слайсера: placeholder G-code и расчёт по пресетам."""
    job.slot_assignments.all().delete()
    presets = list(MaterialPreset.objects.all()[:4])
    if not presets:
        raise RuntimeError("В БД нет MaterialPreset. Запустите: python manage.py seed_materials")

    for i, p in enumerate(presets):
        SlotAssignment.objects.create(
            job=job,
            slot_index=i,
            material_preset=p,
            length_mm=120.0 + i * 15,
            mass_g=25.0 + i * 5,
            cost=Decimal("50.00") + Decimal(i * 25),
        )

    gcode_name = f"job_{job.pk}_mock.gcode"
    content = b"; MOCK GCODE generated by SLICER_MODE=mock\nG28\n"
    job.gcode_file.save(gcode_name, ContentFile(content), save=False)

    if os.getenv("MOONRAKER_UPLOAD_MOCK", "0") == "1":
        moonraker = MoonrakerClient()
        filename = moonraker.upload_gcode(job.gcode_file.path)
        job.moonraker_job_id = moonraker.start_print(filename) or ""

    job.status = "ready"
    job.save()
