# Generated by Django 6.0.3 on 2026-03-28 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU')], default='PLA', max_length=20)),
                ('color_hex', models.CharField(max_length=7)),
                ('density_g_per_cm3', models.FloatField(default=1.24)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('converted_stl', models.FileField(blank=True, null=True, upload_to='stl/')),
                ('gcode_file', models.FileField(blank=True, null=True, upload_to='gcode/')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('preview', 'Предпросмотр'), ('slicing', 'Слайсинг'), ('ready', 'Готово'), ('ordered', 'Заказано'), ('error', 'Ошибка')], default='draft', max_length=20)),
                ('upload_kind', models.CharField(choices=[('model', '3D-модель'), ('sketch', 'Эскиз / 2D')], default='model', help_text='Тип загрузки: модель для предпросмотра STL или эскиз с размерами.', max_length=10)),
                ('sketch_width_mm', models.FloatField(blank=True, null=True)),
                ('sketch_height_mm', models.FloatField(blank=True, null=True)),
                ('sketch_thickness_mm', models.FloatField(blank=True, null=True)),
                ('estimated_print_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moonraker_job_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('index', models.PositiveIntegerField()),
                ('selected', models.BooleanField(default=False)),
                ('slot_assignment', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='print_service.printjob')),
            ],
        ),
        migrations.CreateModel(
            name='SlotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveSmallIntegerField()),
                ('length_mm', models.FloatField(blank=True, null=True)),
                ('mass_g', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_assignments', to='print_service.printjob')),
                ('material_preset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='print_service.materialpreset')),
            ],
            options={
                'ordering': ['slot_index'],
                'unique_together': {('job', 'slot_index')},
            },
        ),
    ]
