# Generated by Django 4.2.30 on 2026-06-13 03:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import print_service.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_temp', models.IntegerField(help_text='Максимальная температура сопла в градусах Цельсия')),
                ('build_volume_m3', models.FloatField(help_text='Объем рабочей зоны в кубических метрах')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('temp_range_min', models.IntegerField()),
                ('temp_range_max', models.IntegerField()),
                ('color_hex', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU')], default='PLA', max_length=20)),
                ('color_hex', models.CharField(choices=[('#FF0000', 'Красный'), ('#00FF00', 'Зеленый'), ('#0000FF', 'Синий'), ('#FFFF00', 'Желтый'), ('#FF00FF', 'Пурпурный'), ('#00FFFF', 'Голубой'), ('#FFFFFF', 'Белый'), ('#000000', 'Черный')], default='#FFFFFF', max_length=7)),
                ('density_g_per_cm3', models.FloatField(default=1.24)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/', validators=[print_service.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj', 'ply', 'glb', 'gltf', 'fbx', 'dae', '3ds', 'blend', '3mf', 'x', 'usd', 'usda', 'usdc', 'step', 'stp', 'iges', 'igs'], message='Неподдерживаемый формат 3D-модели. Допустимы: STL, OBJ, PLY, GLB, GLTF, FBX, DAE, 3DS, BLEND, 3MF, X, USD, USDA, USDC, STEP, IGES.'), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'], message='Неподдерживаемый формат изображения. Допустимы: JPG, JPEG, PNG, SVG.')])),
                ('converted_stl', models.FileField(blank=True, null=True, upload_to='stl/')),
                ('converted_glb', models.FileField(blank=True, null=True, upload_to='glb/')),
                ('converted_3mf', models.FileField(blank=True, null=True, upload_to='3mf/')),
                ('gcode_file', models.FileField(blank=True, null=True, upload_to='gcode/')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('preview', 'Предпросмотр'), ('slicing', 'Слайсинг'), ('ready', 'Готово'), ('ordered', 'Заказано'), ('error', 'Ошибка')], default='draft', max_length=20)),
                ('upload_kind', models.CharField(choices=[('model', '3D-модель'), ('sketch', 'Эскиз / 2D')], default='model', help_text='Тип загрузки: модель для предпросмотра STL или эскиз с размерами.', max_length=10)),
                ('sketch_width_mm', models.FloatField(blank=True, null=True)),
                ('sketch_height_mm', models.FloatField(blank=True, null=True)),
                ('sketch_thickness_mm', models.FloatField(blank=True, null=True)),
                ('estimated_print_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moonraker_job_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('index', models.PositiveIntegerField()),
                ('selected', models.BooleanField(default=False)),
                ('slot_assignment', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='print_service.printjob')),
            ],
        ),
        migrations.CreateModel(
            name='SlotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveSmallIntegerField()),
                ('length_mm', models.FloatField(blank=True, null=True)),
                ('mass_g', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_assignments', to='print_service.printjob')),
                ('material_preset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='print_service.materialpreset')),
            ],
            options={
                'ordering': ['slot_index'],
                'unique_together': {('job', 'slot_index')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_service.equipment')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_service.material')),
            ],
            options={
                'indexes': [models.Index(fields=['equipment', 'material'], name='print_servi_equipme_6a8df6_idx'), models.Index(fields=['equipment'], name='print_servi_equipme_59741f_idx')],
                'unique_together': {('equipment', 'material')},
            },
        ),
    ]
