# Generated by Django 4.2.29 on 2026-03-31 12:53

import django.core.validators
from django.db import migrations, models
import print_service.validators


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0003_alter_materialpreset_id_alter_printjob_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='original_file',
            field=models.FileField(upload_to='uploads/', validators=[print_service.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj', '3ds', 'step', 'stp', 'iges', 'igs'], message='Неподдерживаемый формат 3D-модели. Допустимы: STL, OBJ, 3DS, STEP, IGES.'), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'], message='Неподдерживаемый формат изображения. Допустимы: JPG, JPEG, PNG, SVG.')]),
        ),
    ]
