# Generated by Django 4.2.29 on 2026-04-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0004_alter_printjob_original_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_temp', models.IntegerField(help_text='Максимальная температура сопла в градусах Цельсия')),
                ('build_volume_m3', models.FloatField(help_text='Объем рабочей зоны в кубических метрах')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('temp_range_min', models.IntegerField()),
                ('temp_range_max', models.IntegerField()),
                ('color_hex', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_service.equipment')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='print_service.material')),
            ],
            options={
                'indexes': [models.Index(fields=['equipment', 'material'], name='print_servi_equipme_6a8df6_idx'), models.Index(fields=['equipment'], name='print_servi_equipme_59741f_idx')],
                'unique_together': {('equipment', 'material')},
            },
        ),
    ]
