# Generated by Django 4.2.29 on 2026-04-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0005_equipment_material_equipmentmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpreset',
            name='color_hex',
            field=models.CharField(choices=[('#FF0000', 'Красный'), ('#00FF00', 'Зеленый'), ('#0000FF', 'Синий'), ('#FFFF00', 'Желтый'), ('#FF00FF', 'Пурпурный'), ('#00FFFF', 'Голубой'), ('#FFFFFF', 'Белый'), ('#000000', 'Черный')], default='#FFFFFF', max_length=7),
        ),
    ]
