# Generated by Django 4.2.29 on 2026-04-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0006_alter_materialpreset_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='converted_glb',
            field=models.FileField(blank=True, null=True, upload_to='glb/'),
        ),
    ]
