# Generated by Django 4.2.29 on 2026-04-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_service', '0007_printjob_converted_glb'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='converted_3mf',
            field=models.FileField(blank=True, null=True, upload_to='3mf/'),
        ),
    ]
