# Generated by Django 4.2.30 on 2026-06-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "price_per_gram",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.01,
                        max_digits=10,
                        verbose_name="Цена за грамм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
            },
        ),
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "max_temperature",
                    models.IntegerField(
                        default=300, verbose_name="Максимальная температура (°C)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Принтер",
                "verbose_name_plural": "Принтеры",
            },
        ),
    ]
