# Generated by Django 4.2.30 on 2026-06-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("manager", "Менеджер"),
                    ("client", "Клиент"),
                    ("partner", "Партнёр"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
