# Generated by Django 4.2.30 on 2026-06-13 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за грамм')),
            ],
            options={
                'verbose_name': 'Материал (устаревший)',
                'verbose_name_plural': 'Материалы (устаревшие)',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая цена')),
            ],
            options={
                'verbose_name': 'Заказ (устаревший)',
                'verbose_name_plural': 'Заказы (устаревшие)',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('max_temperature', models.IntegerField(verbose_name='Максимальная температура (°C)')),
            ],
            options={
                'verbose_name': 'Принтер (устаревший)',
                'verbose_name_plural': 'Принтеры (устаревшие)',
            },
        ),
        migrations.CreateModel(
            name='OrderParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.FloatField(default=1.0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='orders.order')),
            ],
            options={
                'verbose_name': 'Параметр заказа (устаревший)',
                'verbose_name_plural': 'Параметры заказов (устаревшие)',
            },
        ),
    ]
