# Generated by Django 4.2.29 on 2026-04-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('color_hex', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет (HEX)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за кг')),
                ('weight_g', models.FloatField(default=0, verbose_name='Остаток на складе (г)')),
                ('density', models.FloatField(default=1.25, verbose_name='Плотность (г/см3)')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка часа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Последнее ТО')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='original_file',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stl_file',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Расчетное время (мин)'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Расчетный вес (г)'),
        ),
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Финальная цена'),
        ),
        migrations.AddField(
            model_name='orderparameter',
            name='rotation_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderparameter',
            name='rotation_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderparameter',
            name='rotation_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderparameter',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='gcode_file',
            field=models.FileField(blank=True, null=True, upload_to='gcode/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('repairing', 'На ремонте'), ('slicing', 'В нарезке'), ('ready_to_print', 'Готов к печати'), ('printing', 'Печать'), ('logistics', 'Передан в логистику'), ('completed', 'Доставлен'), ('failed', 'Ошибка')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.material'),
        ),
        migrations.AddField(
            model_name='order',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.printer'),
        ),
    ]
