// Route names and paths
export const ROUTES = {
  HOME: '/',
  LOGIN: '/auth/login',
  ADMIN: '/admin',
  ADMIN_INDEX: '/admin/index',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_EQUIPMENT: '/admin/equipment',
  ADMIN_FINANCE: '/admin/finance',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_USERS: '/admin/users',
  ADMIN_WAREHOUSE: '/admin/warehouse',
  MANAGER: '/manager',
  MANAGER_INDEX: '/manager/index',
  MANAGER_EQUIPMENT: '/manager/equipment',
  MANAGER_WAREHOUSE: '/manager/warehouse',
  CLIENT: '/client',
  CLIENT_INDEX: '/client/index',
  CLIENT_MESSAGES: '/client/messages',
  CLIENT_MY_ORDERS: '/client/my-orders',
  CLIENT_PROFILE: '/client/profile',
  CLIENT_UPLOAD_MODEL: '/client/upload-model',
  PARTNER: '/partner',
  PARTNER_INDEX: '/partner/index',
  PARTNER_MODELS: '/partner/models',
  PARTNER_PAYMENTS: '/partner/payments',
  PARTNER_ROYALTIES: '/partner/royalties',
  CATALOG: '/catalog',
  CATALOG_INDEX: '/catalog/index',
  ORDER: '/order',
  CALCULATOR: '/calculator',
  ABOUT: '/about',
  MODELS: '/models',
  THREEJS_MODEL: '/threejs/model',
  UPLOAD: '/upload',
} as const;

export const ROUTE_NAMES = {
  HOME: 'home',
  LOGIN: 'login',
  ADMIN: 'admin',
  ADMIN_INDEX: 'admin-index',
  ADMIN_ANALYTICS: 'admin-analytics',
  ADMIN_EQUIPMENT: 'admin-equipment',
  ADMIN_FINANCE: 'admin-finance',
  ADMIN_ORDERS: 'admin-orders',
  ADMIN_USERS: 'admin-users',
  ADMIN_WAREHOUSE: 'admin-warehouse',
  MANAGER: 'manager',
  MANAGER_INDEX: 'manager-index',
  MANAGER_EQUIPMENT: 'manager-equipment',
  MANAGER_WAREHOUSE: 'manager-warehouse',
  CLIENT: 'client',
  CLIENT_INDEX: 'client-index',
  CLIENT_MESSAGES: 'client-messages',
  CLIENT_MY_ORDERS: 'client-my-orders',
  CLIENT_PROFILE: 'client-profile',
  CLIENT_UPLOAD_MODEL: 'client-upload-model',
  PARTNER: 'partner',
  PARTNER_INDEX: 'partner-index',
  PARTNER_MODELS: 'partner-models',
  PARTNER_PAYMENTS: 'partner-payments',
  PARTNER_ROYALTIES: 'partner-royalties',
  CATALOG: 'catalog',
  CATALOG_INDEX: 'catalog-index',
  ORDER: 'order',
  CALCULATOR: 'calculator',
  ABOUT: 'about',
  MODELS: 'models',
  THREEJS_MODEL: 'threejs-model',
  UPLOAD: 'upload',
} as const;

export default ROUTES;
